---
new_page_extension: md
auto_deploy: false
admin_path: Forestry
webhook_url: 
sections:
- type: document
  path: README.md
  label: README
  read_only: true
- type: document
  path: src/index.md
  label: Accueil
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - template-post
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_command: npm start
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: src/dist
  instant_preview_command: npm start
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/src"
