---
new_page_extension: md
auto_deploy: false
admin_path: Forestry
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
- type: document
  path: src/index.md
  label: 'index '
- type: directory
  path: src
  label: Source
  create: all
  match: "**/*"
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: src/images
public_path: "/src/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
